### ISSUE TITLE
[Bug] TypeError: regex3.test is not a function

### ISSUE THREAD

**Issue by KaKi87** [kenan238/reblessed#3]
# Example
```js
const
    blessed = require('reblessed'),
    screen = blessed.screen({
        smartCSR: true
    }),
    textbox = blessed.textbox({
        parent: screen,
        top: 0,
        inputOnFocus: true,
        border: 'line',
        height: 3
    });
screen.render();
textbox.focus();
```
# Steps
Run & try typing
# Expected outcome
Typed characters appear
# Actual outcome
```
TypeError: regex3.test is not a function
    at isMouse (/home/kaki/tmp/reblessed/node_modules/reblessed/lib/keys.js:342:17)
    at emitKeys (/home/kaki/tmp/reblessed/node_modules/reblessed/lib/keys.js:124:7)
    at ReadStream.onData (/home/kaki/tmp/reblessed/node_modules/reblessed/lib/keys.js:50:14)
    at ReadStream.emit (events.js:412:35)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at ReadStream.Readable.push (internal/streams/readable.js:206:10)
    at TTY.onStreamRead (internal/stream_base_commons.js:188:23)
```
# Additional info
Running with `blessed` instead of `reblessed` works.

---
Thanks

**Comment by kenan238** [comment]
Alright, im going to check that.

**Comment by kenan238** [comment]
Done! Please see [this commit](https://github.com/kenan238/reblessed/commit/ebba0823df5895665c17ed3845b507c55eab9002)
