### ISSUE TITLE
[Bug] TypeError: widget.aliases is not iterable

### ISSUE THREAD

**Issue by KaKi87** [kenan238/reblessed#4]
# Example
```js
require('reblessed')
```
# Steps
Run
# Expected outcome
Stops without error
# Actual outcome
```
node_modules/reblessed/lib/widget.js:56
for (var key of widget.aliases) {
                       ^

TypeError: widget.aliases is not iterable
    at Object.<anonymous> (node_modules/reblessed/lib/widget.js:56:24)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (node_modules/reblessed/lib/reblessed.js:17:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```
# Additional info
Running with `blessed` instead of `reblessed` works.

---
Thanks

**Comment by kenan238** [comment]
![image](https://user-images.githubusercontent.com/73741117/155751573-c5e770d1-9331-4e03-a0f8-05d5f6556b3e.png)
